### ISSUE TITLE
Tracking List for 4.1 official release

### ISSUE THREAD

**Issue by jrinker03** [stride3d/stride#1409]
#### Items to complete prior to publishing
- [x] #1386 
- [x] #1221
- [x] #1393 
- [x] #1401 
- [x] #1411 
- [x] #1408 
       - **In Review** stride3d/stride-docs#84
- [x] #1410 
       - **In Review** #1420 
- [x] #1417 

#### Publishing
- [x] Release Notes (**Dependent on Item #1386**)
- [x] Intermediate tutorials (**Dependent on Item #1401**) 
- [ ] 4.0.7 edition of Stride.VisualStudio.Package to NuGet.org from official build (**code is ready in 4.0 branch**)
- [x] 5.0.6 edition of Stride.Launcher to NuGet.org from official build (**Dependent on Item #1411)**
- [ ] 4.1.0 edition of Stride.VisualStudio.Package to NuGet.org from official build(**Dependent on Item #1411**)
- [x] 4.1.0.x editions of all main Stride packages to NuGet.org from official build 
- [x] Publish new StrideSetup.exe (**Dependent on Items #1410 & #1417**)
- [ ] Requirements page (**Dependent on Items #1411 & #1408**)

#### Items that can be completed post initial publishing
- [ ] Update [Stride Launcher page](https://doc.stride3d.net/latest/en/manual/stride-launcher/index.html)
- [ ] Update [Getting Started page](https://doc.stride3d.net/latest/en/manual/get-started/install-stride.html)
- [ ] Update [Visual Studio Extension page](https://doc.stride3d.net/latest/en/manual/get-started/visual-studio-extension.html)
- [ ] Update [Launch Stride page](https://doc.stride3d.net/latest/en/manual/get-started/launch-stride.html)
- [ ] Scrub other [Manual](https://doc.stride3d.net/latest/en/manual/index.html) pages and update content and screenshots

**Comment by Aggror** [comment]
Documentation: intemediate PR done 
https://github.com/stride3d/stride/pull/1401 

I will update the specific section in the release notes later this weekend. https://github.com/stride3d/stride/issues/1386

**Comment by tebjan** [comment]
Now that the tutorials are ready, we should move on with this.

**Comment by VaclavElias** [comment]
- [ ] Stride Web - Home Page
    - Mention C# 10, .NET 6 (web search / SEO purpose)
- [ ] Manual - Features Page
    - Mention C# 10, .NET 6 (web search / SEO purpose)
- [ ] Manual - [Install Stride](https://doc.stride3d.net/latest/en/manual/get-started/install-stride.html)
    - New screenshots?
    - No need .NET 4.7.2?

**Comment by VaclavElias** [comment]
Are you ok with these updates? Or any other wording? I would suggest to mention .NET 6 as it does make an attention 
Home Page
![image](https://user-images.githubusercontent.com/4528464/178126919-9e0c1dcd-d2ea-41d1-917a-622d1fd3813b.png)
Feature Page
![image](https://user-images.githubusercontent.com/4528464/178126921-ffd274b0-0867-4491-b117-28c869d45f2b.png)

**Comment by ykafia** [comment]
I'm fine with that, it's simple and straight to the point

**Comment by xen2** [comment]
Release new launcher 5.0.6 on NuGet (fixed a bunch of issues with code signing -- we never released StrideSetup.exe since .NET Foundation code certificate switch).
Still need to deploy website with new StrideSetup.exe

**Comment by xen2** [comment]
- 4.1 is now live
- 4.1 VSIX too
- Website/docs with release notes as well
Still a few things to do, such as VSIX 4.0.7, etc.

**Comment by VaclavElias** [comment]
I have updated Home Page and Features Page https://github.com/stride3d/stride-website/pull/64

**Comment by VaclavElias** [comment]
I can work on this page https://doc.stride3d.net/latest/en/manual/get-started/install-stride.html is that ok?

**Comment by NicusorN5** [comment]
We're approaching 4.2 ... 🤔
