### ISSUE TITLE
[Linux] Issue tracker for Stride Engine Samples

### ISSUE THREAD

**Issue by Jklawreszuk** [stride3d/stride#2496]
# Description

Commit hash at the time of verification : 4c46fdcc4da0021514fbaaea3d432095d164b9b6 or 4.2.0.2232

## Context 

At the current state Stride 3D enables you to build you games on Linux...kind of. While is possible to build your game it may not be possible to run it because of many different runtime issues. The goal is to make clear which samples can be run and which do not work.

## List of Samples (OpenGL)

- Audio
  
  - [ ] Simple audio - App crashes on image click (OpenGL|Vulkan)
    
- Graphics
  
  - [x] AnimatedModel - `Error while compiling GLSL shader. []` #2487
  - [x] CustomEffect    
  - [x] MaterialShader    
  - [ ] SpriteFonts - Need to implement / port Font loading for Linux https://github.com/stride3d/stride/issues/3021
  - [x] SpriteStudioDemo
    
- Games
  
  - [x] JumpyJet
  - [x] SpaceEscape - `Error while compiling GLSL shader. []` #2487
    
- Input
  
  - [x] Gravity Sensor
  - [x] Touch Inputs - not sure about GamePad though
    
- Particles
  
  - [x] Physics Sample - `Error while compiling GLSL shader. []` #2487
    
- Templates
  
  - [x] First Person Shooter - `Error while compiling GLSL shader. []` #2487, game icon is missing
  - [x] Third Person Shooter - `Error while compiling GLSL shader. []` #2487, game icon is missing 
  - [x] Top Down RPG - `Error while compiling GLSL shader. []` #2487,, game icon is missing 
  - [ ] VR Sandbox - Need to implement / port Font loading for Linux, other issues (?) https://github.com/stride3d/stride/issues/3021
    
- Tutorials
  
  - [x] CsharpBegginer - #2487, game icon is missing
  - [x] CsharpIntermediate - #2487, game icon is missing
    
- UI
  
  - [x] GameMenu - `System.Exception: Depth buffer is not the same size as the render target` #2487
  - [x] UIElementLink - `Error while compiling GLSL shader. []` #2487    
  - [x] UIParticles

**Comment by Jklawreszuk** [comment]
I may have found a potential cause for Stride.SimpleAudio crashing. I'm working now on finding a solution 😀
Edit: Well, maybe It'd better to continue my efforts on Stride.Audio port and fix it that way

**Comment by Jklawreszuk** [comment]
Simple audio still crashes after on sprite click :( (4.4.0)

**Comment by Jklawreszuk** [comment]
I coundnt run VR Sandbox : "Shader Texture2DMS could not be found". I'm assuming this error occurs on Windows as well?

**Comment by Jklawreszuk** [comment]
@xen2 Can this issue be reopened?

**Comment by xen2** [comment]
I have adjust our sample tests to also run on Linux.
It seems all the **tested** samples are passing:
https://github.com/xen2/stride/actions/runs/27268691976 (Linux is the last one in the list)

Here is the list of auto-tested samples (nightly from now on)
- AnimatedModel
- CustomEffect
- FirstPersonShooter
- GameMenu
- GravitySensor
- JumpyJet
- MaterialShader
- ParticlesSample
- PhysicsSample
- SpaceEscape
- SpriteFonts
- SpriteStudioDemo
- ThirdPersonPlatformer
- TopDownRPG
- UIParticles

Let me know if you still notice issues (otherwise let's close).

**Comment by Jklawreszuk** [comment]
Sadly, I do :( At least from what I've tested from yesterday. The good thing is that SimpleAudio and Third Person Shooter sample are now working correctly. TopDownRPG is running too but it crashes when you click anything.

**Comment by Jklawreszuk** [comment]
I noticed there have been a lot of changes to the master. I'll try testing all the samples again tomorrow (update:still the same issues)
