### ISSUE TITLE
Major breaking changes tracking

### ISSUE THREAD

**Issue by Doprez** [stride3d/stride#2576]
## Purpose
This issue will be an overview of planned changes that will be breaking to Strides core. This will allow us to consolidate discussions, PRs and issues into a single place for future planning.

## Current PRs
#2404 likely going to be closed in favour of #2574 
#2574 The main PR related to changing the core startup and surface rendering of Stride

## Current Discussions
#2524 The discussion related to strides startup changes
#2210 Tracking for talks about changing to `System.Numerics`

## Tasks
TBD I will fill this out better with breakdowns for what is needed to get going on the above discussions

#### Math
- [ ] Deprecate Stride math extensions in favour of `System.Numerics`
- [ ] Change core math types to the `System.Numerics` equivelent

#### Game startup
- [ ] Change to a more robust `Game.Window` 
- [ ] decouple the `GameWindow` from `GamePlatform` maybe in favour of something that defines just the update/render loop?
- [ ] remove `GameContext` it serves no real purpose and just adds an unnecessary layer. Should use `GameSettings` instead
- [ ] remove cyclical dependencies between systems. Discussed [here](https://github.com/stride3d/stride/discussions/2524#discussioncomment-11286302)

**Comment by Jklawreszuk** [comment]
You can also add my two PRs which can be considered as breaking change:
- https://github.com/stride3d/stride/pull/2186
- https://github.com/stride3d/stride/pull/2261

**Comment by Doprez** [comment]
I added the directx 9 and opengl 2 support to the main checklist but I think @xen2 wasn't convinced to remove metrics last I remember?

I also dont think its a breaking change so Im not sure that we would need to wait for 5.0 if we wanted to merge that in.
